# Generated by Django 3.1.2 on 2020-10-22 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
                ('c', models.CharField(max_length=20)),
                ('d', models.CharField(max_length=20)),
                ('e', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manuscript_detail',
            fields=[
                ('manuscript_key', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Type_choices', models.CharField(choices=[('Invited Review', 'Invited Review'), ('Original Artical', 'Original Artical'), ('Book Review', 'Book Review'), ('Letter To The Editor', 'Letter To The Editor')], max_length=25, verbose_name='Type')),
                ('title', models.CharField(max_length=200)),
                ('running_head', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=500)),
                ('upload_date', models.DateField(default=datetime.datetime.today)),
                ('upload_by', models.EmailField(max_length=254)),
                ('keyword', models.CharField(blank=True, max_length=300, null=True)),
                ('cover_letter', models.FileField(upload_to='pdf/cover_letter/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('book', models.FileField(upload_to='book/pdf')),
            ],
        ),
    ]
