# Generated by Django 3.1.2 on 2020-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_manuscript_manuscript_detail_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(blank=True, max_length=100, null=True)),
                ('file_to_upload1', models.FileField(upload_to='pdf/articlefile1/%y/%m/%d', verbose_name='file_one')),
                ('file_to_upload2', models.FileField(blank=True, null=True, upload_to='pdf/articlefile2/%y/%m/%d', verbose_name='file_two')),
                ('file_to_upload3', models.FileField(blank=True, null=True, upload_to='pdf/articlefile3/%y/%m/%d', verbose_name='file_three')),
                ('desingnation_for_file_one', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manuscript_attached_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(blank=True, max_length=100, null=True)),
                ('first_author', models.EmailField(max_length=254)),
                ('co_author_second', models.EmailField(blank=True, max_length=254, null=True)),
                ('co_author_third', models.EmailField(blank=True, max_length=254, null=True)),
                ('institution_with_address_main_author', models.CharField(max_length=200)),
                ('institution_with_address_second_author', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_with_address_first_author', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manuscript_attached_editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(blank=True, max_length=100, null=True)),
                ('first_editor', models.EmailField(blank=True, max_length=254, null=True)),
                ('second_editor', models.EmailField(blank=True, max_length=254, null=True)),
                ('third_editor', models.EmailField(blank=True, max_length=254, null=True)),
                ('institution_with_address_first_editor', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_with_address_second_editor', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_with_address_third_editor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manuscript_attached_reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(blank=True, max_length=100, null=True)),
                ('first_reviewer', models.EmailField(max_length=254)),
                ('second_reviewer', models.EmailField(blank=True, max_length=254, null=True)),
                ('third_reviewer', models.EmailField(blank=True, max_length=254, null=True)),
                ('institution_with_address_first_reviewer', models.CharField(max_length=200)),
                ('institution_with_address_second_reviewer', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_with_address_third_reviewer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manuscript_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_figures', models.IntegerField()),
                ('number_of_color_figures', models.IntegerField()),
                ('number_of_tables', models.IntegerField()),
                ('number_of_words', models.IntegerField()),
            ],
        ),
    ]
