# Generated by Django 3.1.2 on 2020-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_file_upload_manuscript_attached_author_manuscript_attached_editor_manuscript_attached_reviewer_manus'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
