# Generated by Django 3.1.2 on 2020-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201023_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='manuscript_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_email', models.EmailField(max_length=254)),
                ('upload_file', models.FileField(upload_to='article/')),
            ],
        ),
    ]
