# Generated by Django 3.1.2 on 2020-10-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_manuscript_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='dockupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_key', models.CharField(max_length=300)),
                ('your_email', models.EmailField(max_length=254)),
                ('ubload_file', models.FileField(upload_to='dock/article')),
            ],
        ),
    ]
