# Generated by Django 3.1.2 on 2020-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_dockupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockupload',
            name='manuscript_key',
            field=models.CharField(blank=True, default="key-<attribute 'year' of 'datetime.date' objects><attribute 'minute' of 'datetime.time' objects><attribute 'day' of 'datetime.date' objects><attribute 'hour' of 'datetime.time' objects><attribute 'minute' of 'datetime.time' objects><attribute 'second' of 'datetime.time' objects><attribute 'microsecond' of 'datetime.time' objects>", max_length=300, null=True),
        ),
    ]
