# Generated by Django 3.1.2 on 2020-10-25 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201025_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockupload',
            name='manuscript_key',
            field=models.CharField(blank=True, default='key-104511442616', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript_detail',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 10, 45, 11, 436620)),
        ),
    ]
