# Generated by Django 3.1.2 on 2020-10-27 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20201027_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dockupload',
            name='manuscript_key',
            field=models.CharField(blank=True, default='key-103213196165', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript_detail',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 10, 32, 13, 190168)),
        ),
    ]
