# Generated by Django 3.1.2 on 2020-10-28 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20201028_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField(default=datetime.datetime(2020, 10, 28, 4, 44, 26, 691952))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dockupload',
            name='manuscript_key',
            field=models.CharField(blank=True, default='key-44426688955', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript_detail',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 4, 44, 26, 679960)),
        ),
    ]
